---
- name: Ensure UFW is installed
  ansible.builtin.apt:
    name: ufw
    state: present
    update_cache: true

- name: Reset ufw
  community.general.ufw:
    state: reset

- name: Disable everything and enable UFW
  community.general.ufw:
    state: enabled
    policy: deny

- name: Set logging
  community.general.ufw:
    logging: 'on'

- name: Allow ports 8000-8020
  community.general.ufw:
    rule: allow
    port: "8000:8020"
    proto: "tcp"
- name: Allow ports 8000-8020 (UDP)
  community.general.ufw:
    rule: allow
    port: "8000:8020"
    proto: "udp"

- name: Allow HTTP
  community.general.ufw:
    rule: allow
    port: "80"
    proto: "tcp"
- name: Allow HTTPS
  community.general.ufw:
    rule: allow
    port: "443"
    proto: "tcp"

- name: Allow SSH
  community.general.ufw:
    rule: allow
    port: "22"
    proto: "tcp"

- name: Allow Chainflip Prometheus
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: "tcp"
    from: "{{ chainflip_prometheus_server_ip }}"
  when: allow_chainflip_prometheus_server
  with_items:
    - 9100
    - 9256

- name: Allow All Outbound
  community.general.ufw:
    rule: allow
    direction: out
    comment: "Outbound"

- name: Reload UFW
  community.general.ufw:
    state: reloaded
